# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Numpy - 기초

In [6]:
arr1 = np.array([1,2,3]) #1차원 행렬

arr1.shape #(3,)
arr1.dtype #dtype('int32')
arr1.ndim #1

1

In [16]:
arr2 = np.array([[1,2,3],[1,2,3]])  # 2차원 배열

print(arr2, '\n') 
print(arr2.shape, '\n') # (2,3) => 2행 3열인 2차원 배열이다.
print(arr2.ndim)  # 2 => 2차원

[[1 2 3]
 [1 2 3]] 

(2, 3) 

2 



In [ ]:
list3 = [ [ [1,2,3] ] ] # list

arr3 = np.array(list3) # nparray

arr3
arr3.ndim # 3 => 3차원
arr3.dtype
arr3.shape # (1,1,3)

# 컴퓨터는 => 0과 1만 이해할 수 있다. -> 나중에 데이터도 숫자형 데이터로 바꿔주셔야 합니다.

In [18]:
list2 = [1,2,'c']

arr4 = np.array(list2)
arr4

array(['1', '2', 'c'], dtype='<U11')

In [35]:
arr = np.array(["1", "2", "3", "4", "5"])
arr.dtype

# final_arr = arr.astype(np.int64)
# final_arr = arr.astype('int64')
final_arr = arr.astype('float')
print(final_arr)
final_arr.dtype

[1. 2. 3. 4. 5.]


dtype('float64')

# ndarray

In [22]:
arr = np.arange(10)
print(arr)

arr2=arr[0:6]
print(arr2)

#indexing
arr3=arr[-1]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]


# reshape() - 차원과 크기 변경 

In [30]:
arr1 = np.arange(10)
print(arr1, '\n')

arr2 = arr1.reshape(2,5)
print(arr2,'\n')

arr3 = arr1.reshape(5,2)
print(arr3, '\n')

# arr4 = arr1.reshape(3,4) 
#ValueError: cannot reshape array of size 10 into shape (3,4)
#최소 12개가 필요해서 3행 4열은 오류가 나는 것이다. 

arr4 = arr1.reshape(2,-1) #2행 5열
print(arr4)

# arr5 = arr1.reshape(3,-1) 
# ValueError: cannot reshape array of size 10 into shape (3,newaxis)


[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [33]:
arr = np.arange(8)
arr

arr2 = arr.reshape(-1,4)
arr2 #행은 너가 마음대로 하고, 4열로 만들어줘 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(1,10)

arr2 = arr.reshape(3,3)
print(arr2)

arr2[1, 1] # 5
arr2[2,2] # 9

# arr2[0, 0:3] # [1,2,3]
arr2[1, 0:3] # [4,5,6]

# [3,6,9]
arr2[:, 2]

# [[1]
#  [4]]

arr3 = arr2[:2, :1]
arr3